### ISSUE TITLE
Implement signup APIs for emailpassword

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#101]
Related issues:
- https://github.com/supertokens/supertokens-core/issues/78
- https://github.com/supertokens/core-driver-interface/issues/1

## API Logic
Input: email, password

- Normalise the email
- If password is "", throw bad request
- Hash password using bcrypt
- Insert a new row in the users table
   - If error thrown regarding duplicate email, throw EMAIL_ALREADY_EXISTS_ERROR
   - if error thrown regarding duplicate uuid, try doing insert query with different uuid
- return OK response as per CDI

## Databases
- [x] SQLite
- [x] MySQL
- [x] PostgreSQL

**Comment by rishabhpoddar** [comment]
## TODOs:
- [ ] normalise email function in core, Utils.java
- [ ] in mem db query for sign up & error handling
- [ ] sqlite db query for sign up & error handling
- [ ] sign up function
- [ ] Basic testing (for core logic and error handling)
