### ISSUE TITLE
Passkeys Support

### ISSUE THREAD

**Issue by coolbueb** [supertokens/supertokens-core#1046]
## Implementation details

Implemenation docs:
https://docs.google.com/document/d/1G7tO9_dSNi8wur3ajGg4pq-wiHatKDbHv2sBt-uSbQg/edit

## TODO
- [ ] Should passkeys always be dependent email and password users or have it's own users ?
- [ ] Should be a paid feature ?
- [ ] Try using same table for challenges
- [ ] add indexes on timeout column(s) for querying with cron for removal
- [ ] remove schema unused columns (also drop webauth_user_id)
- [ ] check counter implementation should work (safari returning 0 everytime)
- [ ] timestamps use bigint
- [ ] credentials pk should also use app id
- [ ] add tenant id only to challenges table
- [ ] Confirm https://github.com/supertokens/supertokens-core/issues/1046#issuecomment-2370896475
   - [ ] From a security point of view, since we allow all fallback methods, passkeys adds no additional security. Is this ok?
   - [ ] Should we allow adding passkeys to third party login? Seems strange.
   - [ ] Unlike some other providers, we will not allow users to sign up with just a passkey (no password). Is this ok?

**Comment by rishabhpoddar** [comment]
## Suggested flow
- Passkeys would be an add on to other auth methods. This means that users would have to set a password if they are using email password login, or do the full magic link / otp flow if passwordless is being used. For third party as well, they would have to go through the third party sign in first.
- During sign up, we would ask users to set a passkey after their first factor login is setup. This can be configurable by the developer if they want to show this or not.
- During sign in:
   - Users would be prompted for their email / phone number first. If social login is enabled, those options will also be shown. So basically this screen: https://master--6571be2867f75556541fde98.chromatic.com/?path=/story/allrecipes-auth--sign-in (if no social login, then it will just be a screen with enter email or phone number). One exception is that if there is only third party recipe configured, we will still show the email box to enable login with passkeys.
   - If they click on social login, then we will only do social login.
   - If they type in an email / phone number, we will see if there exists a user with that email / phone number that has a pass key (across any tenant). 
      - If there doesn't exist, we will continue with the usual flow. In case only third party recipe is used, we will show the third party login options.
      - If there exists a passkey, we will prompt the user to login with passkeys and have a button on the UI like "Use another method", which will fallback to as if there is no passkeys.

**Comment by victorbojica** [comment]
Should also think about account recovery (lost device that had passkeys) and the constraints that the passkey usage adds to the flows (such as having email input as a separte step in the log in flow).

**Comment by dipeshsingh253** [comment]
Hi @victorbojica , @rishabhpoddar 

It seems I don’t have access to the [implementation document](https://docs.google.com/document/d/1G7tO9_dSNi8wur3ajGg4pq-wiHatKDbHv2sBt-uSbQg/edit). However, I reviewed the comments from @rishabhpoddar, and the flow is clear to me. I’d love to contribute to this task—could you please assign it to me?

Thanks!
