### ISSUE TITLE
Email Verification / User Pagination Release Checklist

### ISSUE THREAD

**Issue by NkxxkN** [supertokens/supertokens-core#157]
# 🚀 Feature

- Email verification
- User Pagination

# 📅 Checklist

### Dev Tag
 - [x] [supertokens-core:3.1](https://github.com/supertokens/supertokens-core/tree/3.1)
 - [x] [supertokens-node:3.3](https://github.com/supertokens/supertokens-node/tree/3.3)
 - [x] [supertokens-auth-react:0.4](https://github.com/supertokens/supertokens-auth-react/tree/0.4)
 - [x] supertokens-website

### Others

 - [supertokens-demo-react:master](https://github.com/supertokens/supertokens-demo-react/tree/master)
     - [x] In progress
     - [x] [PR](https://github.com/supertokens/supertokens-demo-react/pull/2) Ready using supertokens/supertokens-auth-react:0.4 and supertokens/supertokens-node:3.3 github repositories in package.json

 - [supertokens-nextjs-demo:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
     - [x] In progress
     - [x] [PR](https://github.com/supertokens/supertokens-nextjs-demo/pull/5) Ready using supertokens/supertokens-auth-react/tree/0.4 and supertokens/supertokens-node:3.3 github repositories in package.json

### 📚 Documentation

- [x] EmailPassword main documentation update
   - [x] In progress [PR](https://github.com/supertokens/main-website/pull/201)
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/introduction)

- [x] NextJS main documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- [x] nodejs documentation update
   - [x] In progress [PR]()
   - [x] Deployed on [test site](https://test.supertokens.io/docs/nodejs/installation)

- [x] auth-react documentation update
   - [x] In progress [PR](https://github.com/supertokens/main-website/pull/201)
   - [x] Deployed on [test site](https://test.supertokens.io/docs/auth-react/introduction)

### 💻 NPM and core release

 - [x] [supertokens-core:3.1](https://github.com/supertokens/supertokens-core/tree/3.1)
    - Docker update
       - [x] MySQL
       - [x] Postgres
       - [x] MongoDB
    - [x] try.supertokens.io
    - [x] Update SaaS config
 - [x] [supertokens-node:3.3](https://github.com/supertokens/supertokens-node/tree/3.3)
   - [x] Updated tests to use `supertokens-node` from registry.
 - [x] [supertokens-auth-react:0.4](https://github.com/supertokens/supertokens-auth-react/tree/0.4)
   - [x] Updated tests to use `supertokens-node` from npm registry
   - [x] Updated `peerDependencies` to use `supertokens-website` from npm registry
- [x] supertokens-website 

### 🔀 Others

 - [supertokens-react-themes:0.4](https://github.com/supertokens/supertokens-react-themes/tree/X.Y)
   - [x] Updated [PR]() with `supertokens-auth-react` from npm registry
   - [x] Release [theme demo app](https://supertokens-react-themes.surge.sh) on surge using `npm run surge`
   - [x] Published to npm registry

- [supertokens-demo-react:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
   - [x] Updated [PR]() using `supertokens-node` and `supertokens-auth-react` npm registry.
   - [x] Deployed to [demo site](http://emailpassword.demo.supertokens.io/)

 - [supertokens-nextjs-demo:master](https://github.com/supertokens/supertokens-nextjs-demo/tree/master)
     - [x] [PR]() updated using `supertokens-node` and `supertokens-auth-react` npm registry.
     - [x] Merged to master

### 📚 Documentation

- EmailPassword main documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/emailpassword/introduction)

- NextJS main documentation update
   - [x] Deployed on [production site](https://test.supertokens.io/docs/emailpassword/nextjs/supertokens-with-nextjs)

- nodejs documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/nodejs/installation)

- auth-react documentation update
   - [x] Deployed on [production site](https://supertokens.io/docs/auth-react/installation)

**Comment by NkxxkN** [comment]
Only thing left is releasing `npm run surge` @rishabhpoddar  and we can close.
