### ISSUE TITLE
Add ability to get userId from sessionHandle

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#255]
Something like `getUserId(sessionHandle)`

## TODOs:
- [x] update swagger spec & cdi md file
- [x] update node SDK & add tests (basic)
- [ ] update docs
    - [ ] recipe docs for sessions and others
    - [ ] nodeJS docs

**Comment by rishabhpoddar** [comment]
Actually now that I think of this again, we will have three APIs for querying based on session:
- To get JWT payload
- To get Session data
- To get userId

We should just combine them into one API which returns all these three info (from the core's perspective), and then in the node side (user's point of view), we can still have three functions - one for each type of info.

**Comment by nkshah2** [comment]
@rishabhpoddar Just to clarify, we still want to leave these APIs intact
- `/recipe/session/data GET`
- `/recipe/jwt/data GET`

to avoid backward compatibility problems and simple introduce a new one that combines all 3 functionalities?

Also if we are leaving them intact, do we also want to have a separate one for just userId to keep things consistent?

**Comment by rishabhpoddar** [comment]
> to avoid backward compatibility problems and simple introduce a new one that combines all 3 functionalities?
Yes. And also see what other makes sense to return apart from session data, jwt payload and userId

> Also if we are leaving them intact, do we also want to have a separate one for just userId to keep things consistent?
No need. We will mark those other two APIs as deprecated in the Spec. 

---------
You should start by issuing a PR for a new CDI spec for this file: https://github.com/supertokens/core-driver-interface/blob/master/v2.8.0.md

You should also update the issue here: https://github.com/supertokens/core-driver-interface/issues/8 summarising the change you have made.
