### ISSUE TITLE
Error in core regarding key-value

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#282]
```
io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | java.lang.NullPointerException: Cannot read field "createdAtTime" because "this.keyInfo" is null

io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | API threw an exception: /recipe/session/verify

%26 Jul 2021 03:34:34:563 +0000 | ERROR | pid: 3eacd872-a7ec-4590-bb2e-20d60cdfe339 | [http-nio-0.0.0.0-8080-exec-3] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | java.lang.NullPointerException: Cannot read field "createdAtTime" because "this.keyInfo" is null
c	at io.supertokens.session.accessToken.AccessTokenSigningKey.getKey(AccessTokenSigningKey.java:81)
_	at io.supertokens.session.accessToken.AccessToken.getInfoFromAccessToken(AccessToken.java:49)
_	at io.supertokens.session.accessToken.AccessToken.getInfoFromAccessToken(AccessToken.java:95)
@	at io.supertokens.session.Session.getSession(Session.java:157)
[	at io.supertokens.webserver.api.session.VerifySessionAPI.doPost(VerifySessionAPI.java:64)
A	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
I	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159)
A	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
f	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
^	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
X	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
W	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
[	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
R	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
Q	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
U	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
P	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
O	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
U	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
\	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
X	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
T	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
^	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
^	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
W	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
4	at java.base/java.lang.Thread.run(Thread.java:832)
```

## Reason for this error:
In `AccessTokenSigningKey.java`, `removeKeyFromMemory` seems be called in the middle of another API that is calling the `getKey` or `getKeyExpiryTime` function and then doing `this.keyInfo.createdAtTime`. This then results in a `NullPointerException`.

## TODO
- [X] We need to add locking to the `AccessTokenSigningKey` class for reading and writing the `this.keyInfo` object.
- [X] Maybe we can set the `keyInfo` to `null` only if we know that it's not been changed already since we last used it?
- [x] Add tests to make sure that the locks prevent this NullPointerException.
- [ ] Update all 3.4.X cores in SaaS to have this fix (from `3.4.1` or `3.4.0` to `3.4.2`)

**Comment by rishabhpoddar** [comment]
We can't use ReadWrite locks cause if we did, in the `getKey` function, we would have to upgrade from a read lock to a write lock, which may lead to a deadlock (since this write lock would be waiting for other read locks which would be waiting to acquire a write lock).
