### ISSUE TITLE
Add delete user API

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#341]
- For all auth recipes.
- Older discussion: https://github.com/supertokens/supertokens-core/issues/273

## TODO:
- [x] core
- [x] mysql
- [x] postgresql
- [x] CDI
- [x] nodejs (delete-user branch)
- [x] golang (delete-user branch)
- [x] python (delete-user branch)
   - [x] tests
- [x] Docs (delete-user branch)
