### ISSUE TITLE
TOTP / MFA login discussions

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#554]
Google doc link: https://docs.google.com/document/d/1qyd4XmepLJXNC4uURcak-7JbWP0UuzOPSsjBInVAuNk/edit

## TODO:
- [x] Consider seperately mentioning templates vars used in qr (issuerName, secret, provisioner, etc)
- [ ] ~~Fetch user identifier based on first factor?~~
- [ ] ~~Give Rishabh all the touch points between account linking and mfa recipe~~
- [x] ~~Think if there are any session changes required for TOTP verify code and verify device API? ~~
- [x] How to prevent the attack in which the attacker finishes the fist factor and then for second factor (which is totp), they call the create new device API and finish the flow with their new device - even though the user already has an existing device. One idea is to add a claim validator to the create device API that all MFA claims should be completed when this API is called. What other solution is there? Some edge cases with this solution:
   - How will this solution affect the sign up process?
   - What if the user signs up with first factor, logs out, and then signs in  - that time we still want to allow them to set the factor even though it's during sign in.
   - [ ] ~~We decided to prevent this by checking if all factors are completed in the `createDevicePOST` implementation (claim assertion), if there already exists one device. But we should discuss this with the team (TODO)~~
- [ ] ~~We need to get rid of TOTP_NOT_ENABLED_ERROR from the core entirely:~~
   - verifyCode should return  INVALID_TOTP_ERROR
   - verifyDevice should return UNKNOWN_DEVICE_ERROR
   - updateDevice should return UNKNOWN_DEVICE_ERROR
   - removeDevice should return { status: "OK"; didDeviceExist: false }
   - listDevices should return an empty array
- [ ] ~~Need to have a separate API for MFA account linking which is enabled if the MFA feature is enabled and account linking is not. This API will only allow account linking for the purpose of MFA. So you need to enforce that, somehow.~~
   - [ ] ~~One idea is that we disallow linking of accounts across the same recipe ID.~~
- [ ] ~~Devs should be able to set MFA settings for tenants via an API call (similar to how they configure third party providers for tenants via an API call). This should be as flexible as possible.~~
   - [ ] ~~Maybe we can have enableFactorForTenant(tenantId, factorId…) just like we have enableFactorForUser. This is not necessary.. it's just an idea~~
- [x] Figure out changes in core, backend sdk and frontend sdk related to this: https://github.com/supertokens/supertokens-core/issues/554#issuecomment-1748645306
- [x] Check how often do we end up in the MFA chooser screen in auth-react and that has just one choice. This can happen if the next array has > 1 element, such that all but one are not setup and can’t be setup by the user.
   - [x] If this is often, then we need to rethink about the "choose another factor" button in the MFA screen
- [x] Contact support UI on the frontend (this UI will be a part of the session recipe):
   - [x] You are on a factor page which is not setup, and you are not allowed to setup
   - [x] Redirection to an unknown factor id
   - [x] First factor returned from the backend is an empty array
- [x]  Other MFA UI related  todos:
   - [x] logout button on the chooser screen needs change
   - [x] select a second factor copy in the chooser screen needs change
   - [x] New logos for passwordless-factor id (separate for both)
   - [x] Add a back button to the OTP MFA screen which takes users back (regardless of if that causes a redirection back to this screen). Note that this back button should only been shown if the next array has 0 items (indicating that the user has fully logged in, cause if they havent logged in, the back button would do nothing)
   - [x] Add a "choose another factor" button on the MFA screen if next array has more than 1 item
   - [x] Add a logout button to the MFA screen.
- [x] Think about 2FA migration. for example migration of TOTP should not need re-setup of authenticator app
- [x] remove automatic addition of factorId into defaultRequiredUserIdsForUser and provide an easy override instead
- [x] Change type of userContext to Record<string, any>
- [x] MFA tests
- [x] do not return totp in getAllFactorIds
- [x] validateForMultifactorAuthBeforeFactorCompletion update impl to get all initialized recipe factors directly without calling the function getAllAvailableFactorIds
- [x] remove recipe function - getAllAvailableFactorIds
- [x] add an example in getMFARequirementsForAuth as a comment - while completing second factor and the user has first factor + 2 other factors setup, we want the completed second factor to be part of oneOf, otherwise it would result in 3FA. we would like this to be a opt in 2FA by default
- [x] in docs mention getMFARequirementsForAuth must be overridden for 3FA
- [x] think about migration of older sessions with all cases
- [x] should refetch for MFA claim should return true for older sessions and then fetchValue should rebuild the next array (move the impl from mfa info endpoint)
- [x] should throw will never happen error in isAllowedToSetupFactor where mfa claim value is missing
- [x] remove tenant id checks in determining factors setup for user
- [x] we are not considering recipeEnabled for tenant in get mfa info endpoint
- [x] we should not check tenantId when return in getFactorsSetupForUser (because factors are app wide)
- [x] create a list of contact support cases
- [x] check what can be removed from checking the dynamic login methods on the frontend
- [x] getDefaultRequiredFactorsForUser make it appwide
- [x] remove functions duplicated for accountlinking in MFA (in core) 
- [x] remove functions duplicated for accountlinking in MFA in the SDK call accountlinking recipe functions directly
- [x] remove validateForMultifactorAuthBeforeFactorCompletion & createOrUpdateSessionForMultifactorAuthAfterFactorCompletion from recipe interface and make them helper functions
- [x] use the overwriteSession flag in session to determine whether to call createNewSession or not instead of handling it inside
- [x] in createOrUpdateSessionForMultifactorAuthAfterFactorCompletion implementation, recurse fetching sessionUser if we get RECIPE_USER_ID_ALREADY_LINKED_WITH_PRIMARY_USER_ID_ERROR while calling createPrimaryUser. also do this for INPUT_USER_IS_NOT_A_PRIMARY_USER while linking accounts
- [x] add contact support error when RECIPE_USER_ID_ALREADY_LINKED_WITH_ANOTHER_PRIMARY_USER_ID_ERROR happens while linkingAccounts. 
  - [x] @porcellus also needs to look at this
- [x] Check all new status codes and if they display right
- [x] Update phone-password example to use MFA
- [x] Update `create-supertokens-app` (maybe?)
- [x] Add an example that allows users to select an email address to use if they have multiple ones (later)
- [x] Re-check style customization
- [x] Re-check Changelog
- [x] Check if we need to remove the completed in another tab screen from OTP MFA (merge issue)
- [x] Update tests after BE behaviour changes (to default requirements) are finalized
- [x] Multitenancy
  - [x] createOrUpdate tenant,app, cud
      - [x] totpEnabled boolean 
      - [x] firstFactors & defaultMFARequirements
  - [x] getTenant API should return firstFactors and defaultMFARequirements
- [x] MFA related
  - [x] new account linking APIs required for MFA
  - [x] remove factor enabled related changes
  - [x] paid user stats
      - [x] MFA related
      - [x] TOTP related
      - [x] TODO in inmemory
- [x] MFA license checks in
  - [ ] ~~createOrUpdate tenant, app, cud if firstFactors or defaultMFARequirements are set & non empty~~
  - [x] new account linking APIs
  - [ ] ~~if totpEnabled is true in tenant/app/cud creation~~
  - [x] in the TOTP APIs
- [x] remove TOTP feature and related checks
- [x] Auth recipes
  - [x] Sign in / up APIs should return if the corresponding factor was present in firstFactors config for that tenant
- [x] Add tests with 1 million users in the core
- [ ] ~~New structure for firstFactors in tenant creation~~
- [x] Remove plugin interface for MFA
- [x] Add API to import TOTP device
- [x] Add created_at for devices and probably add clean up of unverified devices later on
- [x] Add core version to logging
- [x] See the unnecessary changes in core and revert them. eg. isValidFirstFactor in signInUp APIs
- [x] In docs, add a link to storybooks (https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/auth-page--playground).
- [x] Migration docs should take content from: https://supertokens.slack.com/archives/C051BN9QJUX/p1702061857434489
- [x] Core 1 million user test
- [x] IsFactorSetup should return false if fake emails are used in third party (otp-email) - based on fake email format
- [x] https://supertokens.slack.com/archives/C051BN9QJUX/p1702562017159699
- [x] https://supertokens.slack.com/archives/C051BN9QJUX/p1702556911972539
- [ ] Add feature in license key in backend API
- [ ] supertokens.com Dashboard checklist doesn't make too much sense anymore
- [ ] Allow MFA to be enabled via the supertokens.com dashboard.
- [x] add mfa example in create-supertokens-app CLI.
- [x] https://supertokens.slack.com/archives/C051BN9QJUX/p1701777966569869
- [x] All checklist items here: https://github.com/supertokens/docs/pull/763#issue-2045174901
- [x] https://supertokens.slack.com/archives/C051BN9QJUX/p1702814144389259
- [ ] Add MFA examples to angular and vue
- [x] add these validations in core - https://github.com/supertokens/supertokens-core/issues/554#issuecomment-1748645306
- [x] finalize on MFA flows considering overwrite session flag
- [x] Update getLoginMethods to use firstFactors info. ensure it is tested for all possibilities
- [x] core changes
  - [x] change defaultRequiredFactordIds to requiredSecondaryFactors
  - [x] remove `totpEnabled`
  - [x] for known factor IDs in firstFactors and requiredSecondaryFactors array, we should only allow them in the array if the factor is enabled in the core for that tenant, else we should throw a 400 error.
  - [x] firstFactors & requiredSecondaryFactors cannot be an empty array, instead, we can tell users to set it to null to remove it.
  - [x] update list tenant and get tenant to return first factor and secondary factors (undefined if empty)
- [x] Change https://github.com/supertokens/supertokens-auth-react/tree/master/examples/with-emailverification-with-otp to use passwordless otp instead of doing the custom hack
  - [x] Need to manual test after BE has been updated
- [x] Update auth react SDK for deciding if we should ask for email or not in the factor screen to be:
```
(emails.length > 0 && query param has setup (is missing || is false)) -> call createCode
(emails.length === 0 || query param has setup=true) -> show enter email screen
```
- [x]  On the pre built UI sdk, need to make sure that the redirect to path is respected along with its query params.
  - [x] Need to run the test after BE has been updated
- [x] Auto init user metadata recipe in the backend sdk
- [x] Remove totpEnabled from tenant config in the core
- [x] Validation check for tenantConfig when creating / updating tenant. For example, if firstFactors or requiredSecondaryFactors contains email-otp, then passwordless must be enabled.
- [x] Please tell me points of failures:
    - I do MFA.init with no license key in the core
    - I do MFA.init with just account linking license key
    - I do Accountlinking.init with MFA license key license key in the core
    - I do Accountlinking.init with no license key in the core
- [x] Backend should throw if firstFactors is an empty array
- [x] Login methods api should return firstFactors along with other recipe stuff - first factors should be from tenant config if defined else static config (filter based on enabled recipes for the tenant) if defined, else return undefined
- [x] Frontent changes for login method based on this - https://supertokens.slack.com/archives/C051BN9QJUX/p1702990830888489
- [x] In backend, add tests for recursion points of MFA
  - [ ] especially when a new user created becomes a different primary user, we should return 011 and not 010
- [x] Change allOf to allIfInAnyOrder in the backend SDK. 
- [ ] Create an example for step up auth in the settings page before a factor setup is allowed.
- [ ] ~Add `access-denied` special factor id + change the way `n` array is computed to take into account the claims that cannot be currently setup.~ We decided not to do this cause of: https://supertokens.slack.com/archives/C051BN9QJUX/p1703693273706539?thread_ts=1703668285.242759&cid=C051BN9QJUX
- [x] Sign in up APIs can return 403 (from isAllowedToSetup validator), check for it's impact on the frontend SDK
- [x] Update FDI for 403 errors
- [x] given the new set of changes, please tell me the number of requests to the core per sign in / up API call with different stuff enabled (like account linking enabled vs disabled, mfa enabled vs disabled, both enabled vs disabled)
- [x] INVALID_FIRST_FACTOR - add support case
- [x] CANNOT_LINK_FACTOR_ACCOUNT - make it a separate support case
- [x] how to determine factorId for validation in createCodePOST?
  - [x] We'll do this by adding a `factorIds` parameter to `createCodePOST`
- [x] Move "account linking to existing session" to the account linking recipe https://supertokens.slack.com/archives/C051BN9QJUX/p1704732840982139
- [x] Modify example app of account linking where we link third party / password accounts post sign in to just call the pre built APIs, and not have to create manual APIs.
- [x] Frontend UI for the below should have the back button instead of the choose another factor button:
   - https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/totp-mfa--device-setup-multiple-next-options 
   - https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/passwordless-mfa--setup-with-multiple-next-options
   - https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/totp-mfa--verification-with-multiple-next-option
   - https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/passwordless-mfa--verification-with-multiple-next-options
- [x] SOMETHING_WENT_WRONG_ERROR in access denied screen should mention that we need to reload.
- [x] add a test case : discord -> email-otp -> emailverification. Here, the user will have to use their own email for email-otp and not the discord email (in case it's fake), and the email verification claim should pass cause it treats fake emails as verified anyway
- [x] CHeck the number of core api calls for sign in / sign up with mfa / account linking enabled / disabled.
- [x] Add events for totp recipe.
- [x] Add a prop called `isFactorFactor` in the SUCCESS event for all auth recipes on the frontend.
- [x] Change the title on this screen: https://6571be2867f75556541fde98-xieqfaxuuo.chromatic.com/?path=/story/totp-mfa--device-setup-with-single-next-option from “Enable TOTP” to “Add a TOTP device”. Cause this screen is reused when creating a new TOTP device.
- [x] Update http://localhost:3000/docs/session/common-customizations/sessions/jwt-signing-key-rotation to remove the current warning, and instead say that updating will cause a spike in refresh api calls.
- [x] Update docs for claim validators to have the new access token payload arg in fetchValue function.
- [x] Ensure next js test doesn't run on node 16. 
- [ ] Also add parallel tests in CICD to test with node 16 and node 18 in parallel. Node 18 should run the next js tests.
- [x] Change the frontend to treat thirdparty factor id as a custom factor.
- [ ] ~in sign up API in core for emailpassword, we need to mark email as verified if it's a fake email. We also need to prevent sign in for first factor in emailpassword if it's a fake email.~
- [x] Changing how fake emails are generated and checked for in all SDKs.
- [x] In core, update consume code API to accept createNewRecipeUser optional boolean (true by default)
- [x] Change account linking example app in auth-react repo to remove the manual apis for adding new third party to an existing user.
- [x] Include configured firstFactors and requiredSecondaryFactors in multitenancy stats
- [x] See how many core calls will happen from older session without MFA claim and when that is used during a MGAClaim validator.
- [x] Make fake email as verified in core for email password sign up
- [x] Make sure SDK is backwards compatible with older FDI version
- [x] Add proper description to with-multifactorauth-recovery-codes example app
- [x] Change the backup code demo app to take the user to the generate backup code screen rigth after sign up or when they have already used their recovery code and created a new device.
- [x] remove factor id input from create code API of passwordless recipe and also from the frontend functions
- [x] we should do session account linking in sign in recipe function as well
- [x] backwards compatibility needs to be there for frontend and backend sdks
- [x] We should always attempt account linking in sign in recipe functions, similar to how we do in sign up recipe functions
- [x] We will create a new recipe function called `verifyCredentials` in emailpassword based recipes and also expose that. That will only call the core to verify credentials and not do account linking. Also, this function will be called by the signIn recipe function internally (as opposed to it calling the core)
- [x] Remove the `shouldAttemptAccountLinkingIfAllowed` input from everywhere.
- [x] in email password recipe in core, if the email is a fake one, we mark it as verified in the sign up api
- [x] remove the verifyCode after it is implemented in the core
- [x] remove active user in account linking
- [x] see all side efffects of GET APIS in core and the effect of caching of it from the backend sdk
- [x] Core needs to merge with 8.0 branch, and make sure it enforces public tenant in certain APIs ONLY if the CDI version is >= 5.0
- [x] add index on usermetadata table or fixing the populate useridmapping or create the missing index for useridmapping table
- [x] changelog and db migration script for core, plugins

**Comment by rishabhpoddar** [comment]
# SQL Table schema

**Comment by rishabhpoddar** [comment]
# Core APIs

**Comment by rishabhpoddar** [comment]
# Core API logic flow

## /totp/... POST
- Validate input
   - validation logic
- Query db to get XYZ.. 
...

**Comment by rishabhpoddar** [comment]
# Backend SDK API interface (node js)

**Comment by rishabhpoddar** [comment]
# TODO
- [ ] Generate secretKey for user. It should be a random 32char base32 string.
   - Confirm 32 is fine.
- [ ] Confirm that 90 seconds should be the time window for a code or something else?
- [ ] Change verify API to also check for brute force issue.
- [ ] /totp/device/verify also needs to account for device already verified state
- [ ] modify /totp/device/remove to not return unknown_device_error cause we already have a boolean in the OK status for this
- [ ] update POST /totp/device/update path and logic
- [ ] update GET /totp/devices path

**Comment by rishabhpoddar** [comment]
## TODO for 2fa in general

- [ ] Account for other 2fa types:
   -  Email OTP / magic link (passwordless recipe)
   - SMS OTP / magic link (passwordless recipe)
   - TOTP (totp recipe)
   - other custom method that we don't support
- [ ] Allowing developers to specify the 2fa that the app needs
- [ ] Allowing developers to specify 2fa that each user has enabled
- [ ] How this ties into 2fa session claim?

```ts
recipeList: [
   MultiFactorAuth.init({
      factors: [
         [{factor: "thirdpartyemailpassword", required: boolean}],
         [
            {factor: "totp", required: false},
            {factors: "email-otp", required: true}
         ],
         ...
      ],
   })
]
```

**Comment by rishabhpoddar** [comment]
# Core config
TODO: We need to allow changing of time period and skew.

**Comment by KShivendu** [comment]
## SQL Table Schema:

```sql
CREATE TABLE IF NOT EXISTS mfa_factor (
    user_id VARCHAR(128) NOT NULL, -- Assume this is final user ID after account linking feature is completed.
    factor_order INTEGER NOT NULL, -- Factor order. This is the position of the factor in the user's list of factors. There can be multiple factors at the same position.
    factor_type VARCHAR(36) NOT NULL, -- Type of factor. Can be "totp", "email-otp", "sms-otp", etc. Alternatively can be called as factor_flow or factor_name
    status VARCHAR(36) NOT NULL, -- "disabled/enabled/configured" (maybe enumerate)
    PRIMARY KEY (user_id, factor_order, factor_type)
);
```

- The reason for order and type in primary key is it if user wants to have multiple modes in same factor order. Example: TOTP as well as email-otp in 2nd factor.

**Comment by KShivendu** [comment]
## Core API spec

- Should we reuse usermetadata recipe/tables to store all the factor metadata?

### POST /mfa/factor
- disabled => enabled => configured => completed

```json
{
 "user_id": "user_id",
 "factors": [
   [
    // [{"thirdpartyemailpassword": "tpep-user-id"}], // What will happen when account linking is enabled? // No benefit of providing first factor
    [{"totp": "enabled", "email-otp": "disabled"}],  // Just store that factor has been enabled/disabled/configured.
   ],
  ]
}
```

```json
{
 "status": "OK"
}
```

### GET /mfa/factor/list

### Request body:

```json
{
 "user_id": "<user-id-after-account-linking>"
}
```

#### Response body: 
```json
{
 "status": "OK",
 "factors": [
    [{"thirdpartyemailpassword": "enabled"}] 
    [{"totp": "enabled"}, {"email-otp": "enabled"}, ]
   ],
}
```

### PUT /mfa/factor

### Request body:
```json
{
 "status": "OK",
 "factors": [
   {"totp": False}
  ]
}
```

### Response body:
```json
{
  "status": "OK | UNKNOWN_FACTOR_ERROR",
  "unknown_factor": "<factor>"
}
```
- Updates enable column of a factor if it's already there. Otherwise, raises error.

**Comment by rishabhpoddar** [comment]
## Changes to passwordless recipe 

- Expose an API which will help the frontend know if it's been configured or not for this user ID.
TODO..

## Changes to emailpassword
- If this is used in step up auth, and if there is no emailpassword user for the logged in user, we will ask the user to create a password.
TODO

## Changes to thirdparty
- If using this in step up auth, and if there is no thirdparty user, then you ask them to choose an account (and then that is linked)

## Changes to totp
- If not configured, we will ask the user to setup.

## TODO:
- We need to make this configurable -> can be possibly done via overrides in some way??
- Think about this whole flow.

**Comment by KShivendu** [comment]
Including step up auth in factors and mark them as completed ?

**Comment by KShivendu** [comment]
factor[]:
[{id: string, order: number}]
- config
- per userID


db:
userId -> factor[]

nextFactor(session?, completedFactors?, factors, userContext) => string[]
- session will be optional during first factor auth
- completedFactors is from the session if the session is available
- factors is from the static config, unless there is a mapping in the db from session.getUserId() to factor[]
- origibal impl of this function will simply get the next factor from the factors array based on order and the last order in the completedFactors array



Structure of claim in access token:
{
	st-mfa: {
		v: {
			id: string,
			t: …,
			completed: boolean,	
			order: number
		}[]
	}
}

mfaclaim:
	- fetchValue
		- call nextFactor
	- completeFactorWithId
		- mark all the factors with id completed
	- completeFactorWithIdAndOrder
		- mark the factor with ID and order as completed
	- isCompletedWithId
	- isCompletedWithIdAndOrder
	- validators:
		- hasCompletedFactors (factor[]?)
			- if input is empty, it will check for all factors being completed
				- in this case, the function will call next_factor and see if that returns empty, then completed, else not completed.
		- hasCompletedFactorsWithinTime(factor[]?, time)
			- returns success if all factors in the input have been completed within time

————————
Problems:
- nextFactor needs the factors for the user, but that requires a db call. So doing that on each API call is bad
- Function body of validators is not clear.

**Comment by KShivendu** [comment]
Alternatives considered:

## Alt 1
What if we dump all the factors from the DB/config in the first factor login itself. FE can just follow that order.

### Pros:
- Very few DB calls. Fire and forget for BE.
- 

### Cons:
- If step-up auth happens, hasCompletedFactorsWithinTime throws an error so FE redirects to the factor completion page. 
-

**Comment by rishabhpoddar** [comment]
# About first factor login:

## Tenant creation:
- During tenant creation, we will specify which will be the first factors:
```
{
    "tenantId": "customer1",
    "thirdPartyEnabled": true,
    "emailPasswordEnabled": true,
    "firstFactors": ['f1', 'f2', ...]
}
```
- So the core will check that for each `fN` in the firstFactors list, if it's a known `fN` (for example emailpassword, or thirdparty), then that must also be enabled for this tenant. Otherwise send a 400 error. For unknown `fN` (like biometric), we just let it be as part of the first_factors and don't do anything with it.
- firstFactors is optional argument, and by default it will be null in the db, which is != empty array. An empty array should just be treated as no first factors which is useless, but it's fine.

## If frontend uses dynamic login method: true
- The frontend will call getLoginMethods API. This API will get the info from the tenant.
   - If the tenant has a configured firstFactors array (even if it's empty), it will return that
   - If there is nothing configured  on the core, it will check if the user has defined the firstFactors array in the typeInput of the backend SDK, and if that's there, we will return the intersection of that and the enabled login methods for the tenant.
   -  If the backend sdk's firstFactor is also not defined, then we return the auth recipes that are enabled for this tenant.

**Comment by rishabhpoddar** [comment]
## About passwordless factor ID
Instead of having factor id for passwordless where we have "otp-mobile" etc.. we just have it as "passwordless", and in passwordless init, we define:
```
passwordless.init({
	contact_method: “…”,
	flow_type: “..”,
	mfa: {
		contact_method: “…”
	}
})
oneOf: […]
```
- The `mfa` object doesn't have flow type cause we don't support magic link

**Comment by porcellus** [comment]
Planned return values for the default implementations of `getMFARequirementsForAuth`, `getMFARequirementsForFactorSetup`

| Initialized recipes | First factors | Linked accounts (login methods) | Has TOTP device | getMFARequirementsForAuth(oneOf) | getMFARequirementsForFactorSetup(oneOf) |
|---------------------|---------------|---------------------------------|-----------------|----------------------------------|-----------------------------------------|
| TP, EP, TOTP        | undefined     | TP                              | No              | [totp]                           | []                                      |
| TP, EP, TOTP        | undefined     | TP                              | Yes             | [totp]                           | [totp]                                  |
| TP, EP, TOTP        | undefined     | TP, EP                          | No              | [totp]                           | []                                      |
| TP, EP, TOTP        | undefined     | TP, EP                          | Yes             | [totp]                           | [totp]                                  |
| TP, EP, TOTP        | TP            | TP, EP                          | No              | [totp, emailpassword]            | [emailpassword, totp]                   |
| TP, EP, TOTP        | TP            | TP, EP                          | Yes             | [totp, emailpassword, totp]      | [emailpassword, totp]                   |

**Comment by porcellus** [comment]
Factor ids associated with each recipe:
- EmailPassword: `emailpassword`
- ThirdParty: `thirdparty`
- Passwordless: `otp-phone`, `otp-email`, `link-phone`, `link-email`
- TOTP: `totp`
- Other non-auth recipes do not have any factorIds associated with them.
- Combination recipes: the union of the "sub-recipes"

**Comment by rishabhpoddar** [comment]
# How would factorsSetUpByTheUser be determined when calling getMFARequirementsForAuth?

- Each recipe will tell the MFA recipe if the factor controlled by that recipe is setup. 
- For example, if the user has done passwordless.init, then that recipe will just check if the user object contains an email, AND the contact_method of the init config contains email, to add `email-otp` as a factor id that is setup.
- Another example is that if the user has totp.init, then that recipe will check if the user has a totp device that is verified, and if they do, then will add "totp" as a setup factor.

# How will the `defaultMFARequirementsForUser` be determined when calling getMFARequirementsForAuth?
- It will be read from the usermetadata recipe's `_supertokens.defaultMFARequirements` list.
- This also means that we will auto init the usermetadata recipe if it's not already initialised by the dev.

**Comment by rishabhpoddar** [comment]
# Implementation of getMFARequirementsForFactorSetup

- Return `{oneOf: intersection(union(defaultMFARequirementsForUser, defaultMFARequirementsForTenant), factorsSetUpByTheUser)}`

**Comment by porcellus** [comment]
Using the example of TOTP (it works the same for other factors):
- we decided to only show the totp entry screen if the user has a device set up even if they could set up a new device
- we decided that there will be no way (link, button etc) to go from one to the other (setting a device up <-> entering the totp), ignoring the case where this is an optional third factor
- the dev (or the user) can try and force going to the setup screen if by adding a setup=true queryparam

**Comment by rishabhpoddar** [comment]
# Edit: 19th oct, 2023

We decided to drop the custom vs in built factor typing in the node sdk, and just make the FirstFactor type a string[]

**Comment by porcellus** [comment]
we decided to add a created at (or similar) col into the devices table:
- this will enable us to auto clean up old devices (we can add this later if necessary)
- it seems like a useful info in general

**Comment by porcellus** [comment]
Meeting notes:
- we'll change the behaviour of sign in/up APIs to NOT overwrite the session if one already exists, but still return success (status: "OK" )
- apps will be able to revert to the old behaviour through a flag added to the session recipe (`overwriteSessionDuringSignIn`)
- we will only allow factor setup when signing up (i.e.: do not link pre-existing accounts through the MFA recipe)

**Comment by rishabhpoddar** [comment]
# EDIT: 23rd Novembe, 2023

For the default implementation of `isAllowedToSetupFactor`, we only check if the next array is empty.

**Comment by porcellus** [comment]
Implementing recovery codes (will be added as part of an example app):
1. Add API endpoints/UI to create/manage recovery codes (e.g.: save these into user metadata)
2. Add an endpoint that'll verify&save a recovery code into the session payload
3. Override isAllowedToSetupFactor to check if the access token payload has a valid recovery code.
4. Override factor setup to also remove the recovery code from the DB/user metadata
5. Implement a UI flow to reset:
    1. Allow inputting the recovery code
    2. After the recovery code is verified redirect to the factor chooser (or directly to a factor setup page)
    3. Each factor can be forced into "setup mode" by adding ?setup=true  to the URL or by overriding 
    4. getFactorsSetUpByUser to return empty if the user has a recovery code in the session.
6. Override UI components to add links pointing to the entry point of the above reset flow

**Comment by porcellus** [comment]
FE TODOs:
- [ ] Check all new status codes and if they display right
- [ ] Update phone-password example to use MFA
- [ ] Update `create-supertokens-app` (maybe?)
- [ ] Add an example that allows users to select an email address to use if they have multiple ones (later)
- [ ] Re-check style customization
- [ ] Re-check Changelog
- [ ] Check if we need to remove the completed in another tab screen from OTP MFA (merge issue)

**Comment by sattvikc** [comment]
BE TODOs:

- [ ] Change type of userContext to Record<string, any>
- [ ] MFA tests

**Comment by sattvikc** [comment]
- no session -> normal operation
- with session:
  - mfa disabled -> no auto account linking and no manual account linking
    - the 2nd account already exists -> no op (do not change the db)
    - the 2nd account does not exist -> isSignUpAllowed -> create a recipe user
  - mfa enabled -> no auto account linking
    - the 2nd account already exists:
      - if user is already linked to first account -> modify session’s completed and next array
      - if user is not already linked to first account -> Contact support case (cause we can’t do account linking here cause the other account may have some info already in it, and we do not call shouldDoAutomaticAccountLinking function)
    - the 2nd account does not exist -> creating and linking (if linking is allowed, if not, we aren’t creating either + isAllowedToSetupFactor + (2nd factor is verification || login method with same email and its verified))

This means, there is no auto account linking happening if a session exists.

**Comment by porcellus** [comment]
Notes from 24.01.02 discussion:
Let’s look at this use-case: 

- the user is required to do email verification before setting up `otp-phone` (let's say to lower sms sending costs)
- They can do this by:
    - Overriding `isAllowedToSetupFactor…` on the BE
    - Adding the MFA validator after the EV validator on the FE (I need to double check, but this can happen based on recipe init order as well)

In this case:

- If we simply filter the next array and only add whatever is available at that point in time:
    - the next array will be empty after an EP sign up
    - this would make requests using that session pass the default MFA claim validator which is definitely not the right thing to do
- If we filter the next array and add a special (`access-denied`) factor:
    - The requests now fail the default MFA claim validator, which is the right thing
    - What updates the next array in the claim? EV endpoints should not care about the MFA claim so they can’t. We’d end up relying on people calling the MFA info endpoint once again.
    - Also we should avoid adding special cases like this if possible

What I propose instead:

- We add a flag (`v: boolean`) to the MFA claim. This will explicitly flag if the session passes the default requirements or not, making it very easy to explain.
- we can add a filtered next options array to the MFA info API response
- we could drop the next array as we only really use it as a flag and as a way to provide hints about where to redirect/what to show on the chooser screen, but that can be achieved in other ways
    - Doing it without increasing the redirection and call-count will require a tiny bit of caching on the FE and/or making the assumption that if you navigated to the factor screen you are allowed to either complete or set it up and just rely on the initial API calls to tell us otherwise.

The way we can communicate implementation for custom UIs:

1. Check if the flag is true
2. If false, call MFA info to see what to do next:
    1. If the available next factors array is empty show an access denied screen
    2. if the available next factors array has a single item go there
    3. if the available next factors array has multiple items show a chooser

If someone wants to get smart and use the next array in the claim (if we choose to leave it there) they can do so, but that would not be the standard recommendation. Our implementation could still use it.

Changes:

- Remove the next array from the claim and add the flag
- Update the related validator to use the flag instead of the next array
- Add a filtered (`in next array && (in isAllowedToSetup || in isAlreadySetup`) next array into the response of MFA info endpoint
- Cache the MFA info response in the FE (we want to avoid adding the email/phone info into the query params and people were confused about using the hash before)
    - One possible solution to explore: cache the info in session storage + add cache key as a query param.
    - check how many requests we make when navigating to/refreshing a protected page, with and without a factor to redirect to
- Update the claim failure redirection impl to use the MFA info API instead of the next array.
- Update the docs to reflect the above recommendations

**Comment by sattvikc** [comment]
**Jan 3, 2024**

Invalid first factor error is not a support code but instead a 401 error. Support codes are only meant to be used when the implementations are all correct but the user is unable to complete something because of an application state. Invalid first factor is either user trying to call unintended API or a dev mistake or a config error.

**Comment by rishabhpoddar** [comment]
This has been released in core version >= 9.0, node SDK version >= 17.0
