### ISSUE TITLE
Implement the EmailPassword related APIs

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#78]
- [x]  [Sign in API](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-711013081)
- [x]  [Sign up API](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-711013959)
- [x]  [Get user API](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-711013446)
- Reset password:
   - [x]  [Create reset password token API](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-711014951)
   - [x]  [Reset password API](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-711015170)
   - [x]  Cronjob to remove old tokens

-------
- [x] Confirm that the method for password reset token generation is fine: https://github.com/supertokens/supertokens-core/issues/78#issuecomment-721951617

**Comment by rishabhpoddar** [comment]
## `/recipe/signin` POST

**Comment by rishabhpoddar** [comment]
## `/user` GET

**Comment by rishabhpoddar** [comment]
`/recipe/signup` POST

**Comment by rishabhpoddar** [comment]
## `/recipe/password-reset/token` POST

**Comment by rishabhpoddar** [comment]
## `/recipe/password-reset` POST

**Comment by bhumilsarvaiya** [comment]
#### Suggested Table structure for the APIs flow mentioned below

```sql
CREATE TABLE `users` (
  `userid` VARCHAR(64) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `pagination_index` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `password_hash` VARCHAR(128) NOT NULL,
  `time_joined` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pagination_index_UNIQUE` (`pagination_index` ASC) VISIBLE);

CREATE TABLE `password_regenerate_tokens` (
  `userid` VARCHAR(64) NOT NULL,
  `token` VARCHAR(256) NOT NULL,
  `token_version
` VARCHAR(256) NOT NULL,
  `token_expiry` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  CONSTRAINT `user_id_constraint`
    FOREIGN KEY (`userid`)
    REFERENCES `users` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
```

### Signup API
 **Input**: email, password
 - Normalise the email
 - If password is "", throw bad request
 - INSERT QUERY:
    ```sql
    INSERT INTO
        users (`userid`, `email`, `time_joined`, `password_hash`)
    VALUES 
        ('93c2d2a0-190d-11eb-bd48-59715e786758', 'mail@user.com', 1603883091944, 'password_hash');
   ```
   - If error thrown regarding duplicate email, throw `EMAIL_ALREADY_EXISTS_ERROR`
   - else if error thrown regarding duplicate uuid, try doing insert query with different uuid (99.99999%, it won't happen)
- return `OK`
> userid will be a UUID

### Generate new token
**Input**: userid
- start transaction
- select user for update from users table
- if no user info found, end transaction and return `UNKNOWN_USER_ID_ERROR`
- Check if a token already exists for this user
   - If yes, then check if it has expired
   - If not, then end the transaction and return the token.
- generate a new reset password token (UUID). Tokens will be versioned
- UPSERT QUERY:
    ```sql
    INSERT INTO
        password_regenerate_tokens (`userid`, `token`, `token_verison`, `token_expiry`)
    VALUES 
        ('93c2d2a0-190d-11eb-bd48-59715e786758', 'new_token', 'new_version', 1603883091944)
    ON DUPLICATE KEY UPDATE
       `token` = 'new_token',
       `token_version` = 'new_version',
       `token_expiry` = 1603883091944
   ```
   - if error thrown regarding duplicate token, try doing upsert query with different token (99.99999%, it won't happen)
- end transaction
- return the new token

### Reset Password API
**Input**: token, password
- start transaction
- select token for update from password_regenerate_tokens table
- if no such token found, end transaction and return `RESET_PASSWORD_INVALID_TOKEN_ERROR`
- if token found but is expired, end transaction and return `RESET_PASSWORD_INVALID_TOKEN_ERROR`
- else the token is correct so update the user's password and remove this token from this password_regenerate_tokens table
- end transaction
- return `OK`

**Comment by rishabhpoddar** [comment]
# Suggested tables
### users table
- Why does `userid` have 64 chars when it will be a UUID?
- On second thought, I am not comfortable using auto increment as its performance, replication, backup / restore implication is unknown. If you can get more details on these matters, that would be good.
- Why did you choose 128 length for `password_hash`?
- What does `(`email` ASC) VISIBLE` mean?
- If `pagination_index` is auto increment, then why does it have a unique index?

### password_regenerate_tokens table
- Why not make the token the primary key? Since this table is about the tokens and not about the user.
- For this table, we might want to store multiple tokens per user later on.
- `token_version` will be a part of the token itself. No need to have another column for it.
- `token` will not be 256 chars long. Can make it 128
- What is `REFERENCES `users` (`userid`)`?
- `userids` will never be updated, so why do we have ` ON UPDATE CASCADE`?

# API feedback:
### Generate new token
- `start transaction` -> what isolation level?
- `select user for update from users table` -> if there is some other API logic also taking a lock on the user, that will end up waiting as well, even though it's not interating with `password_regenerate_tokens` at all. Can we make it so that this API only deals with this table and not another one? 
- What will the cronjob that removes expired tokens do in terms of queries and transactions and locks?
- Let's discuss how this and the cronjob will change for when we have multiple tokens per user

### Reset password API
- `start transaction` -> what isolation level?
- What if the cronjob is running at the same time as the API, and the cronjob ends up deleting the token, while the API is reading it. How will that issue be solved?
- Let's discuss how this and the cronjob will change for when we have multiple tokens per user

---------------
## More TODOs
- Please provide the equivalent for Postgres and SQLite
- For SQLite, there is no `FOR UPDATE`, but that can be emulated via locks in java - and since this is an in-memory db, the locks in java make sense because it's a single process anyway.
- I need you to also write the logic for another table. The table structure is 
   ```SQL
   CREATE TABLE IF NOT EXISTS key_value (
      name VARCHAR(128),
      value TEXT,
      created_at_time BIGINT UNSIGNED,
      PRIMARY KEY(name)
   );
   ```
   Here, we want to add / update an entry in this table such that:
      - If two processes are trying to insert a new value (two different) for the same key, at the end, they both will end up with the same value for that key.
      -  If two processes are trying to update a value (two different) for the same key, at the end, they both will end up with the same value for that key.
      - If two processes are trying to insert / update a value for two different keys, then they should be able to do so freely.

   Finally, if we can achieve the above, then I believe that we can use a similar approach for the "Generate new token" API?

**Comment by bhumilsarvaiya** [comment]
> Why does userid have 64 chars when it will be a UUID?

We can change that to 36. I kept it higher just in case if we want to allow user to give there own user-id later on

> Why did you choose 128 length for password_hash?

This can be according to whatever hashing/encryting function we want to use. 128 is just a place holder. But it is also better to keep a little high if we later want to change the algorithm.

> What does (email ASC) VISIBLE mean?

Even if I had not mentioned `VISIBLE` here, by default, the unique index that is created, is `VISIBLE`. Visible indexes are used by mysql optimizer. MySQL also supports invisible indexes; that is, indexes that are not used by the optimizer. The feature applies to indexes other than primary keys. 

> If pagination_index is auto increment, then why does it have a unique index?

Because I think we should have an index on that column. The reason we have this column in the first place is to enable pagination later on if required for the users table. Which means this column will be used in WHERE clause of the query. Now for smaller data, we don't see much difference in performance. But as the data size grows, having an non-indexed column in a WHERE clause can result in slower query as compared to the indexed ones.

> On second thought, I am not comfortable using auto increment as its performance, replication, backup / restore implication is unknown. If you can get more details on these matters, that would be good.

Well, I agree to that. I'll look into it.

> Why not make the token the primary key? Since this table is about the tokens and not about the user.

We can have token as primary key, Based on the logic above, I thought we would always want to have one-to-one mapping between token and userid.

> For this table, we might want to store multiple tokens per user later on.
> token_version will be a part of the token itself. No need to have another column for it.
> token will not be 256 chars long. Can make it 128

Okay

> What is REFERENCES users (userid)

userid in this table has a foreign key reference to the users table.

> userids will never be updated, so why do we have ON UPDATE CASCADE?

A foreign key reference will always have property for what should happen when the referred row is removed from the referred table (ON DELETE) or is updated in the referred table (ON UPDATE). If we don't set the behavior, it will be set by mysql by default. So instead, it's better to set it explicitly.

**Comment by bhumilsarvaiya** [comment]
> start transaction -> what isolation level?
Read Committed

**Comment by bhumilsarvaiya** [comment]
> What if the cronjob is running at the same time as the API, and the cronjob ends up deleting the token, while the API is reading it. How will that issue be solved?

If token lifetime is 1 hour, the cronjob should always remove tokens that are older than 1 hour + 10 mins (just an example. if the lifetime of token is X, the cronjob should always remove it after X + Y time). Also, this is an extremely rare case unless the token expiry time is very very less.

**Comment by bhumilsarvaiya** [comment]
> What will the cronjob that removes expired tokens do in terms of queries and transactions and locks?

No transactions required, simply remove the rows based on the logic mentioned in the previous [comment](https://github.com/supertokens/supertokens-core/issues/78#issuecomment-718673682)

**Comment by rishabhpoddar** [comment]
> We can change that to 36. I kept it higher just in case if we want to allow user to give there own user-id later on

Yes. Please change your original comment to reflect the same.

> This can be according to whatever hashing/encryting function we want to use. 128 is just a place holder. But it is also better to keep a little high if we later want to change the algorithm.

Yes Okay. We can keep it `256` and also have a column for the algorithm name `hash_algo VARCHAR(10)`. So that we can change the algorithm in the future if the crypto landscape changes.

> Because I think we should have an index on that column. The reason we have this column in the first place is to enable pagination later on if required for the users table.

We can have non-unique index? Cause that's the intention here..

> This also means we can't have a unique index constraint on userid column for this table.

But we can still have an index.. it's just not unique.

> If token lifetime is 1 hour, the cronjob should always remove tokens that are older than 1 hour + 10 mins (just an example. if the lifetime of token is X, the cronjob should always remove it after X + Y time).

I'm sure we can do better than this. This is a hack, and not a solution.

**Comment by bhumilsarvaiya** [comment]
### Generate new token
> Note: The flow allows to have multiple tokens for user

**Input**: userid
- generate new token and insert into `password_regenerate_tokens` table
- return token

### Reset password API
**Input**: token, password
- select from `password_regenerate_tokens` where token value is equal to the input token
- if no such token exists, return `RESET_PASSWORD_INVALID_TOKEN_ERROR`
- get userid associated with the token
- start transaction
- Select all rows from `password_regenerate_tokens` where userid equals to the userid obtained in the above step (`SELECT ... FOR UPDATE`)
- check if the input token exists for the user and is not expired
- if token doesn't exists or if the token is expired, end transaction and return `RESET_PASSWORD_INVALID_TOKEN_ERROR`
- update user's password
- remove all rows from `password_regenerate_tokens` tokens table for this user_id
- end transaction
- return `OK`

**Comment by bhumilsarvaiya** [comment]
> I need you to also write the logic for another table. The table structure is
  ```
  CREATE TABLE IF NOT EXISTS key_value (
     name VARCHAR(128),
     value TEXT,
     created_at_time BIGINT UNSIGNED,
     PRIMARY KEY(name)
  );
  ```
> Here, we want to add / update an entry in this table such that:
> - If two processes are trying to insert a new value (two different) for the same key, at the end, they both will end up with the same value for that key.
- start transaction (Read Committed)
- select .. for update (initially, both process will get null when running this query) 
- call insert query
- for one of the process, duplicate key error will be thrown. For that process, start over again
- end transaction
> - If two processes are trying to update a value (two different) for the same key, at the end, they both will end up with the same value for that key.
- start transaction (Read Committed)
- select .. for update (one process will wait till the value is updated by another process) 
- call update query
- end transaction
> - If two processes are trying to insert / update a value for two different keys, then they should be able to do so freely.
- same as above

**Comment by rishabhpoddar** [comment]
# The method used for password reset token generation:
- We generate a secure random string using `SecureRandom` and then applying `pbkdf2` to it.
- base64 encoding it
- Removing `+`, `/` and `=` from the string (to make it URL safe).

The final token from the above is 128 characters long. An example is:
```
NmNlNjJjNmFkMGQzMzE2Njg5NTVjNTU3MDgwMmEwOWYxMjYxMzI4ZGEyNzc4NzQ1ZTU5MjcwNzYwYzk3OTg4OTBiOGQ5M2Y4NmUxZTVlOTVjMzkyZjJjNjQwYjcyM2U5
```

We then SHA-256 hash it and save that in the db, and return the raw token to the client.

The code for this can be found [here](https://github.com/supertokens/supertokens-core/blob/120084980ddae18834903a56e738ff40df226323/src/main/java/io/supertokens/emailpassword/EmailPassword.java#L80).

---------

@NkxxkN do you think the above method is fine from a security point of view?

**Comment by NkxxkN** [comment]
From a security point of view it looks pretty solid. The 128 characters long is completely uncrackable.

> Removing +, / and = from the string (to make it URL safe).

We could have used URL encode methods to encode base64 characters (basically, replace `+` with `-` and `/` with `_`, remove padding `=`) . Especially if you want to be able to decode it when the user sends it back. In our case do we ever want to decode it? If no then I think that's fine.

**Comment by rishabhpoddar** [comment]
We do not want to decode it. This final string should be as in in the URL which is passed to the backend. I could have used URLEncoding, but I thought it's better to not have to see `%` in places..

**Comment by bhumilsarvaiya** [comment]
If we see the suggestions for password reset tokens on these links: [[1](https://stackoverflow.com/questions/20013672/best-practice-on-generating-reset-password-tokens)] [[2](https://stackoverflow.com/questions/3558291/generate-secret-code-for-password-reset)] [[3](https://security.stackexchange.com/questions/213975/how-to-properly-create-a-password-reset-token)] [[4](https://blog.etleap.com/2017/01/09/generating-password-reset-tokens/)]
- we are generating a very long random token ✅
- we are base64 encoding it to make it URL safe ✅
- we are going to store hash (SHA256) of token in the db ✅
- token is only one time usable ✅

We are covering all recommended good practices for generating a reset password tokens and I think that is good enough.

Also stating here few major reasons why we are not using JWTs for this: (if we ever forget why)
- if that signing key is compromised, all your user’s passwords can be changed
- JWTs have expiry but there's no convenient way to make them single-use. Thus using JWT can make token reusable. i.e. if the token is compromised, it can be used again to regenerate password given that it is not expired
