### ISSUE TITLE
Remove the need for supertokens-sqlite-plugin repo

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-core#88]
There is already an embedded SQLite db inside the core which serves as an in memory db in case an actual DB is not present. Therefore, `supertokens-sqlite-plugin repo` is not really required.

## TODOs:
- [x] Change `supertokens-root` to work without this repo
- [x] Change tests in `supertokens-core` to work without this repo
- [x] Add testing in mem db with CICD
- [x] Upgrade the contributing and building from source docs
