### ISSUE TITLE
Make recipe enabled booleans better

### ISSUE THREAD

**Issue by sattvikc** [supertokens/supertokens-core#979]
## 🐛 Bug Report

Changes to the core:

- ~~When a new tenant is created, we set all enabled booleans to true, and firstFactor array as. When a new tenant is created, we set all enabled boolean to true, and firstFactor undefined for public AND non public tenants.~~
   - ~~EDIT: for non public tenants, we will set it to `[]` by default because:~~
      - ~~Modifying the static list wont affect existing tenant config by default (other than the public tenant).~~
      - ~~Via the UI there is no way to make a tenant have undefined as firstFactors, so it's weird that it starts of as undefined and then there is no way for the UI to go back to that state.~~
- ~~firstFactors array being empty vs not being set needs to be distinguished. firstFactor would be undefined for static config to take into affect.~~
- requiredSecondaryFactor can remain the same as it is right now (no change needed)
- ~~For older CDI ->~~
  - ~~if firstFactor.length > 0, then we only set those enabled flags~~
  - ~~if firstFactor.length === 0, then we have all as false~~
  - ~~if firstFactor is undefined, then we return the booleans as they are (needs to be communicated as a change to developers).~~

-------
- Add two booleans to tenant config:
   - firstFactorFromStaticConfigIfEmpty
   - thirdPartyProviderFromStaticConfigIfEmpty
- For public tenant, they will be true, true by default:
   - If firstFactors is empty / undefined in the tenant config:
      - From dashboard, it will show static config
   - If firstFactor is not empty in tenant config:
      - It will show from firstFactor in tenant config
   - If in dashboard, you remove the last provider -> we set provider to undefined / empty, and this will actually remove it from the tenant cause that boolean should have been set to false. Or rather, our backend SDK api call will set this boolean to false, since there are no providers configured for this tenant by default.
   - If in dashboard, you disable the last first factor -> we set the firstFactors to undefined, and this will actually remove it from the tenant cause that boolean should have been set to false. Or rather, our backend SDK api call will set this boolean to false, since the firstfactor is by default undefined anyway.
- In fact, if for any tenant (including public), we modify the firstFactors or the thirdparty config in any way, we will set these booleans to false for them automatically in the core. Even if it means they are setting the firstFactor to undefined. If the user also passes these booleans as part of the API call, then we set the value in the db to these booleans.

Backend SDK changes:
- It will have to take into account firstFactorFromStaticConfigIfEmpty and thirdPartyProviderFromStaticConfigIfEmpty in its merging logic.
- When creating / updating a tenant, we should remove the option for the enabled booleans from the function signature. The minimum config is still just tenant id.
- New CDI support and not backwards compatible with older CDI
- What will be the effect on the getLoginMethods API??? TODO
- Change to dashboard logic??? TODO

Docs changes
- We should remove enabled booleans from everywhere, and only show firstFactors usage

Migration of tenant config:
- Table schema migrations -> add new columns to the tenant_configs table.
- ~We considered doing a migration wherein we move the current tenant config -> enable all boolean + firstFactors array. But decided not to do cause such few people are using mfa at the moment anyway.~
- We set the value for firstFactorFromStaticConfigIfEmpty and thirdPartyProviderFromStaticConfigIfEmpty to true for ALL tenants since this is the current behaviour.

Things to note:

- Given that all the enabled booleans are true now, it implies that users can create a secondary factor for any factor as long as the recipe for that is init on the backend sdk, and they have an active session.
- There might be a few things in the backend SDK that rely on the fact that the core would have these booleans as false

## Useful informations

(Write what happened. Add screenshots, stacktraces, videos, anything that can help)

## TODO
- [ ] How will this affect SaaS migration given that it's going to affect the master db and not the target db
   - When copying over master db info for a CUD, we will have to insert the two booleans as true in the sql query when migrating from older core to this new one. 
- [ ] Any changes required to the dashbaord / backend apis once this change is done in the context of the tenant screen?
- [ ] Check that this case is fine
    1. create a tenant - now all toggles are off
    2. turn on otp-email in secondary factors -> this also enables passwordless recipe
    3. reload the tenant detail page -> turns on all passwordless factors in the first factors section (since firstFactors array is undefined at this point)
- [ ] ~Initialising new recipe will enable login methods for all tenants by default - think about this~
- [ ] Test third party deletion (for both, public and non public tenant)
    1. there are 2 static configs defined: google and facebook
    2. Delete facebook using the dashboard, google will remain
    3. Delete google using the dashboard, now since this is the last provider, thirdParty login method gets disabled
    4. Now enable thirdParty login method
- [ ] Check if golang and python SDKs require any changes
- [ ] Check for docs changes, esp where it might be weirdly different for node and golang/python
    What providers should you see now? statically defined ones or the last provider that was deleted?
    It should start from no providers
- [ ] Check that when creating a tenant, if the user forgets to add v2 and uses the inputs of v2, there are no undesired side effects. Make sure of this by extracting common function in the tenant creation handling.
- [ ] Return booleans from loginMethodsGET API in the SDK to prevent FDI version from changing
- [ ] check if firstFactors from tenant is going to be considered when MFA is not initialised in the SDK

**Comment by rishabhpoddar** [comment]
## Using backend sdk with CDI 4.0 with new tenant creation using 4.0

When the backend SDK asks for tenant config, we will return the enabled booleans based on:
- We should set firstFactorFromStaticConfigIfEmpty and thirdPartyProviderFromStaticConfigIfEmpty to true for ALL tenants here since it's using older CDI.
- returned emaiPasswordEnabled = tenantConfig.emaiPasswordEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("emailpassword"))
- returned thirdPartyEnabled = tenantConfig.thirdPartyEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("thirdparty"))
- returned passwordlessEnabled = tenantConfig.passwordlessEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("otp-email") || firstFactor.contains("otp-phone") || ...)


## Using backend sdk with CDI 4.0 with new tenant creation using 5.1 (new to be CDI)

When the backend SDK asks for tenant config, we will return the enabled booleans based on:
- returned emaiPasswordEnabled = tenantConfig.emaiPasswordEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("emailpassword"))
- returned thirdPartyEnabled = tenantConfig.thirdPartyEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("thirdparty"))
- returned passwordlessEnabled = tenantConfig.passwordlessEnabled && ((firstFactors.length === 0 && firstFactorFromStaticConfigIfEmpty) || firstFactors.contains("otp-email") || firstFactor.contains("otp-phone") || ...)

**Comment by sattvikc** [comment]
# Database state for tenant

Introduce new state `[]` (empty) for firstFactors and providers

```ts
{
    emailPasswordEnabled: boolean,
    passwordlessEnabled: boolean,
    thirdPartyEnabled: boolean,
    firstFactors?: null | string[], // null, empty, non-empty
    requiredSecondaryFactors: string[], // null, non-empty
    providers: null | Provider[] // null, empty, non-empty
}
```

## Recipe enabled check in core

```ts
isEmailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword')) || (requiredSecondaryFactors != null && requiredSecondaryFactors.includes('emailpassword'))
isThirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) || (requiredSecondaryFactors != null && requiredSecondaryFactors.includes('thirdparty'))
isPasswordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone')) || (requiredSecondaryFactors != null && requiredSecondaryFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))
```

## Backend CDI 4.0, Core APIs 4.0

- Tenants are created using recipe booleans, firstFactors and requiredSecondaryFactors are not exposed in any way
- In creation of Tenant,
  - `firstFactors` is set to `null`, `providers` is set to `null`
  - For public tenant, all recipe booleans are enabled by default
  - For non-public tenant, all recipe booleans are disabled by default

- While returning a tenant:
  - emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
  - thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
  - passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))
  - providers = providers

- While updating a tenant:
  - Setting boolean to false:
    - if emailPasswordEnabled is set to false && firstFactors !== null, remove 'emailpassword' from firstFactors
    - if thirdPartyEnabled is set to false && firstFactors !== null, remove 'thirdparty' from firstFactors
    - if passwordlessEnabled is set to false && firstFactors !== null, remove 'otp-email', 'otp-phone', 'link-email', 'link-phone' from firstFactors
  - Setting boolean to true
    - if emailPasswordEnabled is set to true && firstFactors !== null, add 'emailpassword' to firstFactors
    - if thirdPartyEnabled is set to true && firstFactors !== null, add 'thirdparty' to firstFactors
    - if passwordlessEnabled is set to true && firstFactors !== null, add 'otp-email', 'otp-phone', 'link-email', 'link-phone' to firstFactors

emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))

## Backend CDI 4.0, Core APIs 5.0

- Tenants are created using recipe booleans + firstFactors
- During creation of tenant,
  - `firstFactors` (if not provided) is set to `null`, `providers` is set to `null`
  - For public tenant, all recipe booleans are enabled by default
  - For non-public tenant, all recipe booleans are disabled by default
- During updation of tenant,
  - Update firstFactor to empty array is not allowed
  - Update boolean or firstFactor as per input
- While returning a tenant:
  - emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
  - thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
  - passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))
  - providers = providers

Edge cases:

- If passwordless was enabled explicitly and not added to firstFactors, then passwordless will be shown as disabled for CD 4.0. This is a correct behaviour because the passwordless would have been enabled for second factor, which is unavailable in 4.0

## Backend CDI 4.0, Core APIs 5.1

- Tenants are created using firstFactors only (recipe booleans are not documented to be used)
- During creation of tenant,
  - For public tenant, all recipe booleans are enabled by default, `firstFactors` is set to `null`
  - For non-public tenant, all recipe booleans are disabled by default, `firstFactors` is set to `[]`
- During updation of tenant,
  - Update firstFactors to empty array is allowed
  - Update boolean or firstFactors as per input
- While returning a tenant:
  - emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
  - thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
  - passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))

## Backend CDI 5.0, Core APIs 5.0

- Tenants are created using recipe booleans + firstFactors
- During creation of tenant,
  - `firstFactors` (if not provided) is set to `null`, `providers` is set to `null`
  - For public tenant, all recipe booleans are enabled by default
  - For non-public tenant, all recipe booleans are disabled by default
- During updation of tenant,
  - Update firstFactor to empty array is not allowed
  - Update boolean or firstFactor as per input
- While returning a tenant:
  - emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
  - thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
  - passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))
  - firstFactors = firstFactors !== [] ? firstFactors : null
  - providers = providers

## Backend CDI 5.0, Core APIs 5.1

- Tenants are created using firstFactors only (recipe booleans are not documented to be used)
- During creation of tenant,
  - For public tenant, all recipe booleans are enabled by default, `firstFactors` is set to `null`
  - For non-public tenant, all recipe booleans are disabled by default, `firstFactors` is set to `[]`
- During updation of tenant,
  - Update firstFactors to empty array is allowed
  - Update boolean or firstFactors as per input
- While returning a tenant:
  - emailPasswordEnabled = (firstFactors == null && emailPasswordEnabled) || (firstFactors != null && firstFactors.includes('emailpassword'))
  - thirdPartyEnabled = (firstFactors == null && thirdPartyEnabled) || (firstFactors != null && firstFactors.includes('thirdparty')) && providers != empty
  - passwordlessEnabled = (firstFactors == null && passwordlessEnabled) || (firstFactors != null && firstFactors.includesOneOf('otp-email', 'otp-phone', 'link-email', 'link-phone'))
  - firstFactors = firstFactors !== [] ? firstFactors : null
  - providers = providers !== [] ? providers : null

## Backend CDI 5.1, Core APIs 5.1

- Tenants are created using firstFactors only (recipe booleans are not documented to be used)
- During creation of tenant,
  - For public tenant, all recipe booleans are enabled by default, `firstFactors` is set to `null`
  - For non-public tenant, all recipe booleans are disabled by default, `firstFactors` is set to `[]`
- During updation of tenant,
  - Update firstFactors to empty array is allowed
  - Update boolean or firstFactors as per input
- While returning a tenant:
  - emailPasswordEnabled = emailPasswordEnabled
  - thirdPartyEnabled = thirdPartyEnabled
  - passwordlessEnabled = passwordlessEnabled
  - firstFactors = firstFactors
  - requiredSecondaryFactors = requiredSecondaryFactors
  - providers = providers

## Backend CDI 5.0, Migrated Tenant from 4.0

- firstFactors is set to `null` for all tenants

## Backend CDI 5.1, Migrated Tenant from 4.0

- firstFactors is set to `null` for all tenants

## Backend CDI 5.1, Migrated Tenant from 5.0

- State of `firstFactors` and `providers` are retained

## From dashboard point of view

### For migrated tenant from 4.0

#### firstFactors

- `firstFactors` will be set to null, so in the dashboard we show all available factors based on how SDK is initialised
- Toggling any of the factors will update the `firstFactors` field
- On further updates on `firstFactors`, the firstFactors will never get to the `null` state

#### thirdParty providers

- `providers` will be set to null, so we show all statically defined providers
- Adding or deleting a provider will result in a non-empty value in core
- Any further updates on providers will never result in `providers` to be set to `null`

### For migrated tenant from 5.0

#### firstFactors

- if `firstFactors` was null, then same rules as 4.0 tenant will apply
- On further updates on `firstFactors`, the firstFactors will never get to the `null` state

#### thirdParty providers

- if `providers` was null, then same rules as 4.0 tenant will apply
- Any further updates on providers will never result in `providers` to be set to `null`

### Tenants on 5.1

- While creating a tenant, `firstFactors` and `providers` are set to `[]`

**Comment by sattvikc** [comment]
database states

enabled booleans
  for latest node SDK: filtering out the first and second factors that have boolean set to false
  for py/go SDK: frontend uses subset of this as first factors based on what is initialised in the frontend static config

firstFactors
  null:
    for latest node SDK: use backend static config. It will throw an error on frontend if all the recipes from this array are not initialised
    for py/go SDK: implies all recipe booleans are true
  []:
    for latest node SDK: no login allowed
    for py/go SDK: all enabled booleans are false
  ["emailpassword", "thirdparty"]:
    for latest node SDK: it means we use subset of this based on which recipe is initialised in the backend static config. This will overwrite mfa.init(firstFactors) It will throw an error on frontend if all the recipes from this array are not initialised
    for py/go SDK: only enabled booleans associated with the factors are true, rest false. What is rendered on frontend is subset of this based on which recipe is initialised in the frontend static config

requiredSecondaryFactors
  null:
    for latest node SDK: MFA is not enabled
    for py/go SDK: not applicable
  ["otp-phone"]:
    for latest node SDK: enables subset based on backend SDK initialised recipes (check with Mihaly)
    for py/go SDK: not applicable

providers
  TODO


## create or update in v4.0

### create public tenant
  Intention
  - All recipes are enabled by default and the frontend static config gets used
  - If the backend SDK makes calls to any recipe APIs is allowed

  effect on enabledBoolean
  - all boolean set to true
  effect on firstFactors
  - firstFactors set to all factors
  effect on core APIs
  - core will allow all APIs
  effect on thirdParty providers array
  - no effect


### create non-public tenant
  Intention
  - All recipes are disabled by default
  - If the backend SDK makes calls to any recipe APIs is disallowed

  effect on enabledBoolean
  - all boolean set to false
  effect on firstFactors
  - firstFactors set to []
  effect on core APIs
  - core will block all APIs
  effect on thirdParty providers array
  - no effect

### { emailPasswordEnabled: true }
  Intention
  - Enable emailpassword as a first factor for the tenant
  - If the backend SDK makes calls to emailPassword APIs, it should be allowed in the core

  effect on enabledBoolean
  - emailPassword boolean set to true
  effect on firstFactors
  - modify firstFactors to add emailpassword to it
  effect on core APIs
  - core will allow emailpassword APIs
  effect on thirdParty providers array
  - no effect

### { emailPasswordEnabled: false }
  Intention
  - Disable emailpassword as a first factor for the tenant
  - If all the booleans are false, it means the user has disabled login for the tenant entirely
  - EmailPassword APIs are blocked by the core

  effect on enabledBoolean
  - emailPassword boolean set to false
  effect on firstFactors
  - if firstFactors is null
    - if all booleans are false, set firstFactors = []
    - else add factors that have boolean as true
  - if firstFactors is []
    - do nothing
  - else
    - remove emailpassword from firstFactors (if it exists). if firstFactors becomes empty, leave it empty
  effect on core APIs
  - core will block emailpassword APIs
  effect on thirdParty providers array
  - no effect

similarly for thirdparty and passwordless

## create or update in v5.0

### create public tenant (same as v4)
  Intention
  - All recipes are enabled by default for firstFactor or secondFactor depending on backend static config
  - If the backend SDK makes calls to any recipe APIs is allowed

  effect on enabledBoolean
  - all boolean set to true
  effect on firstFactors
  - firstFactors set to all factors
  effect on core APIs
  - core will allow all APIs
  effect on thirdParty providers array
  - no effect


### create non-public tenant (same as v4)
  Intention
  - All recipes are disabled by default
  - If the backend SDK makes calls to any recipe APIs is disallowed

  effect on enabledBoolean
  - all boolean set to false
  effect on firstFactors
  - firstFactors set to []
  effect on core APIs
  - core will block all APIs
  effect on thirdParty providers array
  - no effect

### { emailPasswordEnabled: true }
  Intention
  - If the backend SDK makes calls to emailPassword APIs, it should be allowed in the core
  - let the sdk use emailpassword as either first or second factor

  effect on enabledBoolean
  - emailPassword boolean set to true
  effect on firstFactors
  - do not modify
  effect on core APIs
  - core will allow emailpassword APIs
  effect on thirdParty providers array
  - no effect

### { emailPasswordEnabled: false }
  Intention
  - EmailPassword is disabled entirely (cannot be used as either first or second factor)
  - EmailPassword APIs are blocked by the core

  effect on enabledBoolean
  - emailPassword boolean set to false
  effect on firstFactors
  - if firstFactors is null
    - do not modify
  - if firstFactors is []
    - do nothing
  - else
    - remove emailpassword from firstFactors (if it exists). if firstFactors becomes empty, leave it empty (do not throw an error)
  effect on core APIs
  - core will block emailpassword APIs
  effect on thirdParty providers array
  - no effect


### { firstFactors: null }
  Intention
  - To use backend static config (mfa.init(firstfactors) or initialized recipes) for firstFactors for the tenant

  effect on enabledBoolean
  - enable all booleans. Note: if the user is returning 'otp-phone' in the getMFAReqForAuth and the user disabled it using passwordlessEnabled = false, then we are re-enabling. This ok because the right way to disable 'otp-phone' is not return in the getMFAReqForAuth override.
  effect on firstFactors
  - set firstFactors to null
  effect on core APIs
  - core will allow all APIs
  effect on thirdParty providers array
  - no effect


### { firstFactors: ["otp-phone"] }
  Intention
  - To allow only otp-phone as first factor and no other first factor for the tenant
  - Ignore Mfa.init(firstFactors) and initialized recipes in the backend SDK and use this value instead

  effect on enabledBoolean
  - enable passwordless (we wont error out as it causes friction)
  effect on firstFactors
  - set firstFactors to ['otp-phone']
  effect on core APIs
  - core will allow all APIs
  effect on thirdParty providers array
  - no effect

### { emailPasswordEnabled: true, firstFactors: null, requiredSecondaryFactors: null }
  - This means that emailPassword is being enabled for either first factor or second factor
  - core should allow emailpassword APIs
  - get in v4.0 should return emailPasswordEnabled true
  - get in v5.0 should return as per the update
  - get in v5.1 (v2 API) ???

### { requiredSecondaryFactors: null }
  - This means that any factor that is enabled can be used as a secondary factor
  - get in v4.0 no booleans should get flipped because of this [rare case]
  - get in v5.0 should return requiredSecondaryFactors: null  and rest as is
  - get in v5.1 (v2 API) should return requiredSecondaryFactors: null (discuss) and firstFactors as is

### { requiredSecondaryFactors : [...]}
  - This means some factors are being enabled as secondary factors
  - get in v4.0 no booleans should get flipped because of this [rare case]
  - get in v5.0 should return requiredSecondaryFactors: [...], rest as is
  - get in v5.1 (v2 API) should return requiredSecondaryFactors: [...] + (factors from enabled recipes - firstFactors) (discuss)

## create or update in v5.1 (v2 API)

### { firstFactors: null }
  - This means that all firstFactors are to be enabled
  - core allows all recipe APIs
  - get in v4.0 should return all the booleans as true
  - get in v5.0 should return all the booleans as true and firstFactors: null
  - get in v5.1 (v2 API) should return firstFactors: null and secondaryFactors as is

### { firstFactors: ['emailpassword']}
  - This means that only emailpassword is enabled as firstFactor
  - core should allow emailpassword APIs
  - get in v4.0 should return only emailPasswordEnabled: true
  - get in v5.0 should return emailPasswordEnabled: true and firstFactors: ['emailpassword'] other booleans can be true based on the secondary factors
  - get in v5.1 (v2 API) return as is

### { firstFactors: [] }
  - This means that all recipes are disabled for firstFactor
  - core blocks all recipes (unless requiredSecondaryFactors contains some factors). probably we should not allow setting requiredSecondaryFactors if firstFactors == []
  - get in v4.0 should return all the booleans as false
  - get in v5.0 may return some booleans true based on secondaryFactors
  - get in v5.1 (v2 API) should return firstFactors: [] and secondaryFactors as is

### { requiredSecondaryFactors: ['emailpassword'] }
  - This means that emailpassword maybe used as a secondary factor
  - core allows emailpassword APIs
  - get in v4.0 should not be affected by this
  - get in v5.0 should have emailPasswordEnabled: true and rest as is
  - get in v5.1 (v2 API) should return requiredSecondaryFactors: ['emailpassword'] and rest as is

**Comment by sattvikc** [comment]
Implemented in core 9.1
